-- Basic
vim.g['mapleader'] = 's'
vim.api.nvim_set_keymap('n', 's', '<Nop>', { noremap = false, silent = true })
vim.api.nvim_set_keymap('n', 'S', '<Nop>', { noremap = false, silent = true })
vim.api.nvim_set_keymap('n', 't', '<Nop>', { noremap = false, silent = true })

vim.api.nvim_set_keymap('n', '<CR>', ':<C-u>w<CR>', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', '<C-p>', '<Up>', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', '<C-n>', '<Down>', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'q', ':q<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<C-w>', ':bd<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'Q', 'q', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'U', '<C-r>', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', '<C-r>', '<Nop>', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', '<C-y>', '<C-v>', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'vy', 'ggVG', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'j', 'gj', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'k', 'gk', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'H', '^', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'L', '$', {noremap = true, silent = false})
vim.api.nvim_set_keymap('v', 'H', '^', {noremap = true, silent = false})
vim.api.nvim_set_keymap('v', 'L', '$', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', ';', ':', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', ':', 'm', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'm', ';', {noremap = true, silent = false})
vim.api.nvim_set_keymap('v', ';', ':', {noremap = true, silent = false})
vim.api.nvim_set_keymap('v', ':', 'm', {noremap = true, silent = false})
vim.api.nvim_set_keymap('v', 'm', ';', {noremap = true, silent = false})
-- EasyMotion
vim.api.nvim_set_keymap('n', ',', '<Plug>(easymotion-s)', {noremap = false, silent = false})
-- HlsLens
vim.api.nvim_set_keymap('n', 'n', "<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'N', "<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '*', "*<Cmd>lua require('hlslens').start()<CR>", { noremap = true })
vim.api.nvim_set_keymap('n', '#', "#<Cmd>lua require('hlslens').start()<CR>", { noremap = true })
vim.api.nvim_set_keymap('n', 'g*', "g*<Cmd>lua require('hlslens').start()<CR>", { noremap = true })
vim.api.nvim_set_keymap('n', 'g#', "g#<Cmd>lua require('hlslens').start()<CR>", { noremap = true })
-- Easy-align
vim.api.nvim_set_keymap('x', 'ga', '<Plug>(EasyAlign)', {noremap = false, silent = false})
vim.api.nvim_set_keymap('n', 'ga', '<Plug>(EasyAlign)', {noremap = false, silent = false})
-- Fterm
vim.api.nvim_set_keymap('n', '<F5>', '<CMD>lua require("FTerm").toggle()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('t', '<F5>', '<C-\\><C-n><CMD>lua require("FTerm").toggle()<CR>', { noremap = true, silent = true })
-- Diff View
vim.api.nvim_set_keymap('n', '<leader>o', ':<C-u>DiffviewOpen<CR>', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', '<leader>c', ':<C-u>DiffviewClose<CR>', {noremap = true, silent = false})
-- LSP
vim.api.nvim_set_keymap('n', '<leader>k', ':lua vim.lsp.diagnostic.goto_prev()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>j', ':lua vim.lsp.diagnostic.goto_next()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>g', ':lua vim.lsp.buf.code_action()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>l', ':lua vim.lsp.buf.formatting()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>h', ':lua vim.lsp.buf.hover()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>s', ':lua vim.lsp.buf.document_symbol()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>m', ':lua vim.lsp.buf.rename()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>]', ':lua vim.lsp.buf.definition()<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>}', ':lua vim.lsp.buf.references()<CR>', {noremap = true, silent = true})
-- Ctrlsf
vim.api.nvim_set_keymap('n', '<leader>f', '<Plug>CtrlSFPrompt', {noremap = false, silent = false})
vim.api.nvim_set_keymap('v', '<leader>f', '<Plug>CtrlSFVwordExec', {noremap = false, silent = false})
vim.api.nvim_set_keymap('n', '<leader>F', '<Plug>CtrlSFCwordExec', {noremap = false, silent = false})
vim.api.nvim_set_keymap('n', '<leader>t', ':CtrlSFToggle<CR>', {noremap = true, silent = false})
-- Browser
vim.api.nvim_set_keymap('n', '<leader>ww', '<Plug>(openbrowser-smart-search)', { noremap = true, silent = true })
-- Markdown
vim.api.nvim_set_keymap('n', '<leader>wm', ':<C-u>MarkdownPreview<CR><CR>', { noremap = false, silent = true })
vim.api.nvim_set_keymap('n', '<leader>wx', ':<C-u>TableFormat<CR>', { noremap = true, silent = true })
-- Basic
vim.api.nvim_set_keymap('n', 'tp', ':<C-u>bprev<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'tn', ':<C-u>bnext<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'tz', ':<C-u>noh<CR>', { noremap = true, silent = true })
-- Layout
vim.api.nvim_set_keymap('n', 'tb', ':<C-u>NvimTreeToggle<CR>', {noremap = true, silent = true})
-- Telescope
vim.api.nvim_set_keymap('n', 'tf', ":lua require('telescope.builtin').current_buffer_fuzzy_find()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'tj', ":lua require('telescope.builtin').live_grep()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'to', ":lua require('plugins.telescope').project_files()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'te', ":lua require('telescope.builtin').buffers()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'tm', ":lua require('telescope.builtin').marks()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'tr', ":lua require('telescope.builtin').treesitter()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 't;', ":lua require('telescope').extensions.project.project{}<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'tg', ":lua require('plugins.telescope').my_git_status()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'tc', ":lua require('plugins.telescope').my_git_bcommits()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'tx', ":lua require('plugins.telescope').my_note()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'td', ':TodoTelescope<CR>', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'ti', ':Octo issue list<CR>', {noremap = true, silent = false})
-- Spectre
vim.api.nvim_set_keymap('n', 'ts', ":lua require('spectre').open()<CR>", {noremap = true, silent = false})
vim.api.nvim_set_keymap('v', 'ts', ":lua require('spectre').open_visual()<CR>", {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'tv', "viw:lua require('spectre').open_visual()<CR>", {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', 'tF', "viw:lua require('spectre').open_file_search()<CR>", {noremap = true, silent = false})
